name: My GitHub Actions Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Platane Snake
      uses: Platane/snk@v2
      with:
        github_user_name: Kamasah-Dickson
        palette: github-dark
        color_snake: green

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: snake-artifacts
        path: |
          dist/github-snake.svg
          dist/github-snake-dark.svg
          dist/ocean.gif
